#!/bin/bash

# v0.1 @2022-12-21

# -c : config file
# -m : mode, get/put, put2 (automatically all missing directories)
# -t : target, such as qlab, qq, .etc


configFile=.rdsync_config
mode=put
target=any
while getopts "c:m:t:" arg
do
    case $arg in 
        c)
            configFile=$OPTARG;;
        m)
            mode=$OPTARG;;
        t)
            target=$OPTARG;;
    esac
done


tarDir=${PWD}
rPath=""
while [[ $tarDir != ~ ]]
do
    if [[ -e $tarDir/$configFile ]]; then
        break
    fi
    rPath=`basename $tarDir`"/$rPath"
    tarDir=`dirname $tarDir`
done
if [[ ! -e $tarDir/$configFile ]]; then
    echo "cannot find $configFile in the current and all parent directories! Error"
    exit 2
fi


echo $tarDir/$configFile
addr=
while read line
do
    eList=($line)
    if [[ $target == any ]]; then
        echo ${line}
        addr=${eList[1]}
        break
    fi
    if [[ "${eList[0]}" == "$target" ]]; then
        addr=${eList[1]}
        break
    fi
done < $tarDir/$configFile

if [ -z "$addr" ]; then
    echo "cannot find target <$target>"
    exit 1
fi

# echo $@
# echo ${@:${OPTIND}}

if [[ "$mode" =~ put.* ]]; then
    echo "entering <put> mode"
    targetFiles="${@:${OPTIND}}"
    if [[ $targetFiles == "" ]]; then
        targetFiles="*"
    fi

    if [[ "$mode" == "put" ]]; then
        rsync -avP $targetFiles $addr/$rPath
    elif [[ "$mode" == 'put2' ]]; then
        mach_addr=(${addr//:/ })
        mach=${mach_addr[0]}
        ssh $mach "mkdir -p ${mach_addr[1]}/$rPath"
        rsync -avP $targetFiles $addr/$rPath
    else
        echo "unsupported mode = ${mode}"
        exit 4
    fi

elif [[ "$mode" == 'get' ]]; then
    targetFiles="${@:${OPTIND}}"
    if [[ ${#targetFiles[@]} -gt 1 ]]; then
        echo "for get, plz only specify one file or one pattern using wildcard '*'"
        exit 3
    fi
    if [[ $targetFiles == "" ]]; then
        targetFiles="*"
    fi
    echo "rsync -av $addr/$rPath/$targetFiles ."
    echo $addr
    echo $rPath
    echo $targetFiles
    rsync -avP $addr/$rPath/$targetFiles .
else
    echo "not supported for $mode yet!"
    exit
fi
